name: Check code on pull requests & subsequent pushes

on:
  pull_request:
    branches:
      - trunk
  push:
    branches:
      - trunk

env:
  AWS_REGION: eu-central-1
  SPRING_PROFILES_ACTIVE: ci,testing

jobs:
  owasp:
    name: owasp
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v3.7.0
        with:
          java-version: 17
          distribution: 'zulu'
      - name: Run owasp dependency check
        uses: gradle/gradle-build-action@v2
        with:
          arguments: dependencyCheckAnalyze
      - name: Archive owasp check results
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: owasp-results
          path: build/reports/dependency-check-report.html
  checkstyle:
    name: checkstyle
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v3.7.0
        with:
          java-version: 17
          distribution: 'zulu'
      - name: Run checkstyle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: checkMain checkTest
      - name: Archive checkstyle results
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: checkstyle-results
          path: build/reports/checkstyle.html
  tests:
    name: tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v3.7.0
        with:
          java-version: 17
          distribution: 'zulu'
      - name: Run tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test --info
      - name: Archive test results
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: test-results
          path: build/reports/tests/test