name: Deploy the service when pull requests are merged

on:
  push:
    branches:
      - trunk

jobs:
  generate-image:
    name: build image and push it to GH container registry
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v3.10.0
        with:
          java-version: 17
          distribution: 'zulu'
      - name: Run JIB
        uses: gradle/gradle-build-action@v2
        with:
          arguments: jib
        env:
          GITHUB_ACTOR: ${{ secrets.GH_ACTOR }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}